wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1640635161
    t:
      1:
      - 1
      3:
      - 16
      4: 3.7.11
      5: 0.12.9
      8:
      - 1
      - 5
      9:
        2: whatsai_code
architecture:
  desc: null
  value: CNN
batch_size:
  desc: null
  value: 128
classes:
  desc: null
  value: 10
dataset:
  desc: null
  value: MNIST
epochs:
  desc: null
  value: 5
kernels:
  desc: null
  value:
  - 16
  - 32
learning_rate:
  desc: null
  value: 0.005
